config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
  @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path
    else
      render 'edit'
    end

    end
  def destroy
      @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order("created_at DESC")

  end

  # pas de suite
  def show
    @post = Post.find(params[:id])

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params_post)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])

end

  def update
    @post = Post.find(params[:id])
    if @post.update(params_post)
    redirect_to post_path
  else
    render 'edit'
  end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path

  end


  private

  def params_post
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.body %></p>
 <%= link_to "edit", edit_post_comment_path(comment.post, comment) %>
 <%= link_to "suprimer", post_comment_path(comment.post, comment), method: :delete %>

app/views/comments/_form.html.erb
<%= form_for [@post, @post.comments.build] do |f| %>

<div class="form-group">

<%= f.text_field :body, class: "form-control" %>
</div>
<%= f.submit "post ton commentaire", class: "btn btn-default btn-primary"%>
  <% end %>

app/views/comments/edit.html.erb
<div class="container">


<h1>Edit comment </h1>

<%= form_for([@post, @comment]) do |f| %>
<div class="form-group">

<%= f.text_field :body, class: "form-control" %>
</div>
	<%= f.submit "edite ton commentaire", class: "btn btn-default btn-primary" %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved or updated:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :titre, class: "col-md-4 control-label"  %>
  <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :body, class: "col-md-4 control-label"   %>
  <%= f.text_field :body, class: "form-control"  %>
  </div>
  <%= f.submit "Cree ton post", class: "btn btn-default btn-primary"%>


<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h2>edit Post</h2>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">


<% @posts.each do |post| %>
  <h2> <%= post.title %> </h2>
  <%= link_to "voir le post", post_path(post), class: "btn btn-default btn-primary" %>
<% end %>

<%= link_to "Nouveau post", new_post_path %>

</div>

app/views/posts/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
<h2> <%= @post.title %> </h2>
<p> <%= @post.body %> </p>
<span><%= time_ago_in_words(@post.created_at) %> </span>

<h3> Commentaire</h3>
<%= render @post.comments %>
<%= render 'comments/form' %>
<br>
<%= link_to "edit", edit_post_path(@post),  class: "btn btn-default btn-primary"%>
<%= link_to "Home", root_path,class: "btn btn-default btn-primary" %>
<%= link_to "suprimer", post_path(@post), method: :delete, data: { confirm: "tu es sur ?"} %>
</div>